services:
  client:
    container_name: client
    build: ./client
    image: yolo_client:${client_tag}
    ports:
      - "3008:3008"
    restart: always
    volumes:
      - ./frontend:/app
    networks:
      - app_network

  api:
    container_name: api
    build: ./backend
    image: yolo_api:${api_tag}
    ports:
      - "5000:5000"
    restart: always
    environment:
      DB_URL: mongodb://db/yolomy
    networks:
      - app_network

  db:
    container_name: db
    image: mongo:4.0-xenial
    ports:
      - "27019:27017"
    restart: always
    volumes:
      - /var/opt/yolomy:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge