services:
  db:
    container_name: db
    image: mongo:4.0-xenial
    ports:
      - "27019:27017"
    restart: always
    volumes:
      - /var/opt/yolomy:/data/db
    networks:
      - app_network

  backend:
    container_name: backend
    build: ./backend
    image: yolo_backend:${api_tag}
    ports:
      - "5000:5000"
    restart: always
    environment:
      DB_URL: mongodb://db/yolomy
    networks:
      - app_network

  client:
    container_name: client
    build: ./client
    image: yolo_client:${client_tag}
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app_network

  nginx_server:
    container_name: nginx_server
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - client
    networks:
      - app_network

networks:
  app_network:
    driver: bridge